### PR TITLE
Python Support

### PR DESCRIPTION
**Pull request by iudeen**
- [x]  Implement base functionality
- [x] Implement Tests
- [x] ~Support for XML?~

### CODE REVIEW

**Comment by iudeen** [comment]
@rabbagast I see that there is also an XML file, should I add support for that as well?

**Comment by rabbagast** [comment]
No, not needed. The XML is the old Energistics version of the standard, kept there for reference mainly,

**Comment by rabbagast** [comment]
Hi! Great work! Beautiful code! Some feedback:

- The folder for uom.json has been changed from "json" to "standard" to better reflect its content (and since it contains xml also :-)
- The _description_ is removed from quantity: It does not give any added value, and is anyway null for most of them.
- You don't need to support unit aliases (but you can). These are not part of any standard, but something I have added for working with legacy well log files that uses non-standard unit symbols.  
- Your implementation of display units can be simplified. Use the value in uom.json instead of the logic you found in UnitManager.java. This logic is anyway now gone as I have done similar simplifications there.

**Comment by iudeen** [comment]
Thanks! I'm held up a bit this week on my day job. Will try to incorporate your feedback very soon!

**Comment by iudeen** [comment]
@rabbagast all feedback is addressed. 

Do you plan on pushing this to PyPi repository? I can package this and have a wheel file ready to publish as well.

**Pull request merged**
